// if you don't specify a html file, the sniper will generate a div with id "rootDiv"
//const app = require("biojs-vis-circular-bar-chart");
const VisCircularBarChart = require("biojs-vis-circular-bar-chart");


  
let data; // a global
const redditThread = "/api/v2/pokemon-color/purple";
const redditUrl = "pokeapi.co";
const redditPath = redditThread + ".json";
const proxy = "cors-anywhere.herokuapp.com/";
const url = redditUrl;
const myData = [
                {
                        "name": "rattata",
                        "url": "http://pokeapi.co/api/v2/pokemon-species/19/",
                        "details": {
                          "capture_rate": "500",
                          "cute": false
                        }
                },
                {
                        "name": "ekans",
                        "url": "http://pokeapi.co/api/v2/pokemon-species/23/",
                        "details": {
                          "capture_rate": "1000",
                          "cute": true
                        }
                },
                {
                        "name": "nidoran-m",
                        "url": "http://pokeapi.co/api/v2/pokemon-species/32/",
                        "details": {
                          "capture_rate": "300",
                          "cute": true
                        }
                },
                {
                        "name": "zubat",
                        "url": "http://pokeapi.co/api/v2/pokemon-species/41/",
                        "details": {
                          "capture_rate": "200",
                          "cute": true
                        }
                },
                {
                        "name": "venonat",
                        "url": "http://pokeapi.co/api/v2/pokemon-species/48/",
                        "details": {
                          "capture_rate": "1023",
                          "cute": true
                        }
                },
                {
                        "name": "arbok",
                        "url": "http://pokeapi.co/api/v2/pokemon-species/24/",
                        "details": {
                          "capture_rate": "300",
                          "cute": true
                        }
                }];

const alleleFreq = [
{"Chrom":6,"Position":"ju","RSID":".","Reference":"G","Alternate":"T","Consequence":"","Protein Consequence":"","Transcript Consequence":"c.-51G>T","Filter":"PASS","Annotation":"5' UTR","Flags":"","Allele Count":2,"Allele Number":39742,"Number of Homozygotes":0,"Allele Frequency":0.00005032,"Allele Count African":0,"Allele Number African":1898,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":2614,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":21970,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":934,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":2956,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":298,"Homozygote Count Other":0,"Allele Count South Asian":2,"Allele Number South Asian":9072,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738403,"RSID":".","Reference":"G","Alternate":"A","Consequence":"","Protein Consequence":"","Transcript Consequence":"c.-41G>A","Filter":"PASS","Annotation":"5' UTR","Flags":"","Allele Count":2,"Allele Number":40190,"Number of Homozygotes":0,"Allele Frequency":0.00004976,"Allele Count African":0,"Allele Number African":1914,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":2678,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":22184,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":950,"Homozygote Count Finnish":0,"Allele Count Latino":1,"Allele Number Latino":3028,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":298,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":9138,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738410,"RSID":".","Reference":"C","Alternate":"T","Consequence":"","Protein Consequence":"","Transcript Consequence":"c.-34C>T","Filter":"PASS","Annotation":"5' UTR","Flags":"","Allele Count":1,"Allele Number":40704,"Number of Homozygotes":0,"Allele Frequency":0.00002457,"Allele Count African":0,"Allele Number African":1964,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":2746,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":22434,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":966,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":3100,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":298,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":9196,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738422,"RSID":".","Reference":"A","Alternate":"G","Consequence":"","Protein Consequence":"","Transcript Consequence":"c.-22A>G","Filter":"PASS","Annotation":"5' UTR","Flags":"","Allele Count":2,"Allele Number":42106,"Number of Homozygotes":0,"Allele Frequency":0.0000475,"Allele Count African":2,"Allele Number African":2028,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":2942,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":23264,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":1008,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":3238,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":304,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":9322,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738438,"RSID":".","Reference":"G","Alternate":"T","Consequence":"","Protein Consequence":"","Transcript Consequence":"c.-6G>T","Filter":"PASS","Annotation":"5' UTR","Flags":"","Allele Count":1,"Allele Number":44154,"Number of Homozygotes":0,"Allele Frequency":0.00002265,"Allele Count African":1,"Allele Number African":2124,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":3196,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":24448,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":1104,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":3520,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":320,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":9442,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738442,"RSID":".","Reference":"C","Alternate":"T","Consequence":"","Protein Consequence":"","Transcript Consequence":"c.-2C>T","Filter":"PASS","Annotation":"5' UTR","Flags":"","Allele Count":2,"Allele Number":44400,"Number of Homozygotes":0,"Allele Frequency":0.00004505,"Allele Count African":0,"Allele Number African":2144,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":3230,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":24578,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":1124,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":3532,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":320,"Homozygote Count Other":0,"Allele Count South Asian":1,"Allele Number South Asian":9472,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738450,"RSID":".","Reference":"G","Alternate":"A","Consequence":"p.Asp3Asn","Protein Consequence":"p.Asp3Asn","Transcript Consequence":"c.7G>A","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":43878,"Number of Homozygotes":0,"Allele Frequency":0.00002279,"Allele Count African":0,"Allele Number African":2176,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":3190,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":24202,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":1140,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":3486,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":310,"Homozygote Count Other":0,"Allele Count South Asian":1,"Allele Number South Asian":9374,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738462,"RSID":".","Reference":"G","Alternate":"C","Consequence":"p.Asp7His","Protein Consequence":"p.Asp7His","Transcript Consequence":"c.19G>C","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":3,"Allele Number":43572,"Number of Homozygotes":0,"Allele Frequency":0.00006885,"Allele Count African":0,"Allele Number African":2170,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":3220,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":23898,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":1142,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":3504,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":306,"Homozygote Count Other":0,"Allele Count South Asian":3,"Allele Number South Asian":9332,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738467,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.Thr8Thr","Protein Consequence":"p.Thr8Thr","Transcript Consequence":"c.24C>T","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":5,"Allele Number":41638,"Number of Homozygotes":0,"Allele Frequency":0.0001201,"Allele Count African":1,"Allele Number African":2060,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":3048,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":4,"Allele Number European (Non-Finnish)":22852,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":1060,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":3290,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":300,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":9028,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738471,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.Pro10Ser","Protein Consequence":"p.Pro10Ser","Transcript Consequence":"c.28C>T","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":40224,"Number of Homozygotes":0,"Allele Frequency":0.00002486,"Allele Count African":0,"Allele Number African":1986,"Homozygote Count African":0,"Allele Count East Asian":1,"Allele Number East Asian":2946,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":21936,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":1008,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":3168,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":286,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":8894,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738475,"RSID":".","Reference":"G","Alternate":"A","Consequence":"p.Ser11Asn","Protein Consequence":"p.Ser11Asn","Transcript Consequence":"c.32G>A","Filter":"PASS","Annotation":"missense","Flags":"MNP","Allele Count":1,"Allele Number":38824,"Number of Homozygotes":0,"Allele Frequency":0.00002576,"Allele Count African":0,"Allele Number African":1894,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":2866,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":21192,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":940,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":2994,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":274,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":8664,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738476,"RSID":".","Reference":"C","Alternate":"A","Consequence":"p.Ser11Arg","Protein Consequence":"p.Ser11Arg","Transcript Consequence":"c.33C>A","Filter":"PASS","Annotation":"missense","Flags":"MNP","Allele Count":2,"Allele Number":38372,"Number of Homozygotes":0,"Allele Frequency":0.00005212,"Allele Count African":0,"Allele Number African":1882,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":2814,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":2,"Allele Number European (Non-Finnish)":20926,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":942,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":2948,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":270,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":8590,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738486,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.His15Tyr","Protein Consequence":"p.His15Tyr","Transcript Consequence":"c.43C>T","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":32936,"Number of Homozygotes":0,"Allele Frequency":0.00003036,"Allele Count African":0,"Allele Number African":1502,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":2320,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":17918,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":806,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":2236,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":238,"Homozygote Count Other":0,"Allele Count South Asian":1,"Allele Number South Asian":7916,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738496,"RSID":".","Reference":"C","Alternate":"G","Consequence":"p.Pro18Arg","Protein Consequence":"p.Pro18Arg","Transcript Consequence":"c.53C>G","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":23126,"Number of Homozygotes":0,"Allele Frequency":0.00004324,"Allele Count African":0,"Allele Number African":892,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":1388,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":12544,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":418,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":1152,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":176,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":6556,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738497,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.Pro18Pro","Protein Consequence":"p.Pro18Pro","Transcript Consequence":"c.54C>T","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":1,"Allele Number":18358,"Number of Homozygotes":0,"Allele Frequency":0.00005447,"Allele Count African":0,"Allele Number African":596,"Homozygote Count African":0,"Allele Count East Asian":1,"Allele Number East Asian":958,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":9944,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":278,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":716,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":144,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":5722,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738502,"RSID":".","Reference":"G","Alternate":"A","Consequence":"p.Arg20Gln","Protein Consequence":"p.Arg20Gln","Transcript Consequence":"c.59G>A","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":16976,"Number of Homozygotes":0,"Allele Frequency":0.00005891,"Allele Count African":0,"Allele Number African":536,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":806,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":9048,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":262,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":610,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":138,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":5576,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738507,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.Arg22Trp","Protein Consequence":"p.Arg22Trp","Transcript Consequence":"c.64C>T","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":13804,"Number of Homozygotes":0,"Allele Frequency":0.00007244,"Allele Count African":1,"Allele Number African":348,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":490,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":7232,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":156,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":352,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":106,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":5120,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738526,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.Ala28Val","Protein Consequence":"p.Ala28Val","Transcript Consequence":"c.83C>T","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":6716,"Number of Homozygotes":0,"Allele Frequency":0.0001489,"Allele Count African":0,"Allele Number African":208,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":120,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":1664,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":20,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":88,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":60,"Homozygote Count Other":0,"Allele Count South Asian":1,"Allele Number South Asian":4556,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738531,"RSID":".","Reference":"C","Alternate":"G","Consequence":"p.Arg30Gly","Protein Consequence":"p.Arg30Gly","Transcript Consequence":"c.88C>G","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":16,"Allele Number":10004,"Number of Homozygotes":0,"Allele Frequency":0.001599,"Allele Count African":0,"Allele Number African":338,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":170,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":15,"Allele Number European (Non-Finnish)":2678,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":28,"Homozygote Count Finnish":0,"Allele Count Latino":1,"Allele Number Latino":132,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":98,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":6560,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738532,"RSID":".","Reference":"G","Alternate":"A","Consequence":"p.Arg30His","Protein Consequence":"p.Arg30His","Transcript Consequence":"c.89G>A","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":2,"Allele Number":9886,"Number of Homozygotes":0,"Allele Frequency":0.0002023,"Allele Count African":0,"Allele Number African":326,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":162,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":2554,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":22,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":132,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":100,"Homozygote Count Other":0,"Allele Count South Asian":1,"Allele Number South Asian":6590,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738576,"RSID":".","Reference":"G","Alternate":"A","Consequence":"p.Val45Ile","Protein Consequence":"p.Val45Ile","Transcript Consequence":"c.133G>A","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":12864,"Number of Homozygotes":0,"Allele Frequency":0.00007774,"Allele Count African":0,"Allele Number African":724,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":212,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":3918,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":10,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":170,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":126,"Homozygote Count Other":0,"Allele Count South Asian":1,"Allele Number South Asian":7704,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738583,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.Ala47Val","Protein Consequence":"p.Ala47Val","Transcript Consequence":"c.140C>T","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":13632,"Number of Homozygotes":0,"Allele Frequency":0.00007336,"Allele Count African":0,"Allele Number African":918,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":250,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":4422,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":16,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":178,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":130,"Homozygote Count Other":0,"Allele Count South Asian":1,"Allele Number South Asian":7718,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738607,"RSID":".","Reference":"T","Alternate":"C","Consequence":"p.Phe55Ser","Protein Consequence":"p.Phe55Ser","Transcript Consequence":"c.164T>C","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":15394,"Number of Homozygotes":0,"Allele Frequency":0.00006496,"Allele Count African":0,"Allele Number African":1246,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":350,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":5640,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":16,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":230,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":140,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":7772,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738625,"RSID":".","Reference":"G","Alternate":"C","Consequence":"p.Cys61Ser","Protein Consequence":"p.Cys61Ser","Transcript Consequence":"c.182G>C","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":2,"Allele Number":15772,"Number of Homozygotes":0,"Allele Frequency":0.0001268,"Allele Count African":0,"Allele Number African":1328,"Homozygote Count African":0,"Allele Count East Asian":2,"Allele Number East Asian":358,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":5884,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":16,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":242,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":150,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":7794,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738653,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.Arg70Arg","Protein Consequence":"p.Arg70Arg","Transcript Consequence":"c.210C>T","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":1,"Allele Number":14842,"Number of Homozygotes":0,"Allele Frequency":0.00006738,"Allele Count African":0,"Allele Number African":1022,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":366,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":5226,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":20,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":252,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":148,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":7808,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738659,"RSID":".","Reference":"G","Alternate":"T","Consequence":"p.Gly72Gly","Protein Consequence":"p.Gly72Gly","Transcript Consequence":"c.216G>T","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":1,"Allele Number":15290,"Number of Homozygotes":0,"Allele Frequency":0.0000654,"Allele Count African":0,"Allele Number African":1180,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":376,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":5504,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":20,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":248,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":150,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":7812,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738668,"RSID":".","Reference":"G","Alternate":"A","Consequence":"p.Glu75Glu","Protein Consequence":"p.Glu75Glu","Transcript Consequence":"c.225G>A","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":3,"Allele Number":15382,"Number of Homozygotes":0,"Allele Frequency":0.000195,"Allele Count African":0,"Allele Number African":1218,"Homozygote Count African":0,"Allele Count East Asian":3,"Allele Number East Asian":376,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":5558,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":24,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":254,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":156,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":7796,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738673,"RSID":".","Reference":"G","Alternate":"A","Consequence":"p.Ser77Asn","Protein Consequence":"p.Ser77Asn","Transcript Consequence":"c.230G>A","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":29,"Allele Number":15430,"Number of Homozygotes":1,"Allele Frequency":0.001879,"Allele Count African":0,"Allele Number African":1236,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":382,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":5580,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":22,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":256,"Homozygote Count Latino":0,"Allele Count Other":1,"Allele Number Other":158,"Homozygote Count Other":0,"Allele Count South Asian":27,"Allele Number South Asian":7796,"Homozygote Count South Asian":1},
{"Chrom":6,"Position":43738674,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.Ser77Ser","Protein Consequence":"p.Ser77Ser","Transcript Consequence":"c.231C>T","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":1,"Allele Number":15434,"Number of Homozygotes":0,"Allele Frequency":0.00006479,"Allele Count African":0,"Allele Number African":1242,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":382,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":5576,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":24,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":254,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":158,"Homozygote Count Other":0,"Allele Count South Asian":1,"Allele Number South Asian":7798,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738692,"RSID":".","Reference":"T","Alternate":"C","Consequence":"p.Ala83Ala","Protein Consequence":"p.Ala83Ala","Transcript Consequence":"c.249T>C","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":1,"Allele Number":14836,"Number of Homozygotes":0,"Allele Frequency":0.0000674,"Allele Count African":0,"Allele Number African":1094,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":348,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":5226,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":22,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":236,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":152,"Homozygote Count Other":0,"Allele Count South Asian":1,"Allele Number South Asian":7758,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738696,"RSID":".","Reference":"T","Alternate":"G","Consequence":"p.Ser85Ala","Protein Consequence":"p.Ser85Ala","Transcript Consequence":"c.253T>G","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":4,"Allele Number":14618,"Number of Homozygotes":0,"Allele Frequency":0.0002736,"Allele Count African":0,"Allele Number African":1062,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":328,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":5096,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":18,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":226,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":148,"Homozygote Count Other":0,"Allele Count South Asian":4,"Allele Number South Asian":7740,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738705,"RSID":".","Reference":"G","Alternate":"T","Consequence":"p.Glu88Ter","Protein Consequence":"p.Glu88Ter","Transcript Consequence":"c.262G>T","Filter":"PASS","Annotation":"stop gained","Flags":"","Allele Count":1,"Allele Number":14360,"Number of Homozygotes":0,"Allele Frequency":0.00006964,"Allele Count African":0,"Allele Number African":1020,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":310,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":4928,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":26,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":218,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":148,"Homozygote Count Other":0,"Allele Count South Asian":1,"Allele Number South Asian":7710,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738727,"RSID":".","Reference":"G","Alternate":"A","Consequence":"p.Gly95Glu","Protein Consequence":"p.Gly95Glu","Transcript Consequence":"c.284G>A","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":13542,"Number of Homozygotes":0,"Allele Frequency":0.00007384,"Allele Count African":1,"Allele Number African":798,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":296,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":4460,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":24,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":196,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":146,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":7622,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738777,"RSID":".","Reference":"G","Alternate":"C","Consequence":"p.Gly112Arg","Protein Consequence":"p.Gly112Arg","Transcript Consequence":"c.334G>C","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":8492,"Number of Homozygotes":0,"Allele Frequency":0.0001178,"Allele Count African":0,"Allele Number African":422,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":194,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":2566,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":26,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":96,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":76,"Homozygote Count Other":0,"Allele Count South Asian":1,"Allele Number South Asian":5112,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738782,"RSID":".","Reference":"T","Alternate":"C","Consequence":"p.Ala113Ala","Protein Consequence":"p.Ala113Ala","Transcript Consequence":"c.339T>C","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":1,"Allele Number":7666,"Number of Homozygotes":0,"Allele Frequency":0.0001304,"Allele Count African":1,"Allele Number African":386,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":180,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":2288,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":12,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":86,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":68,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":4646,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738891,"RSID":".","Reference":"G","Alternate":"T","Consequence":"p.Ala150Ser","Protein Consequence":"p.Ala150Ser","Transcript Consequence":"c.448G>T","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":12974,"Number of Homozygotes":0,"Allele Frequency":0.00007708,"Allele Count African":1,"Allele Number African":610,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":672,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":4798,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":456,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":438,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":114,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":5886,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738905,"RSID":".","Reference":"CGAG","Alternate":"C","Consequence":"p.Glu156del","Protein Consequence":"p.Glu156del","Transcript Consequence":"c.466_468delGAG","Filter":"PASS","Annotation":"inframe deletion","Flags":"","Allele Count":1,"Allele Number":28666,"Number of Homozygotes":0,"Allele Frequency":0.00003488,"Allele Count African":0,"Allele Number African":1506,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":1800,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":13308,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":1086,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":1560,"Homozygote Count Latino":0,"Allele Count Other":1,"Allele Number Other":262,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":9144,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738906,"RSID":".","Reference":"G","Alternate":"A","Consequence":"p.Glu155Lys","Protein Consequence":"p.Glu155Lys","Transcript Consequence":"c.463G>A","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":30970,"Number of Homozygotes":0,"Allele Frequency":0.00003229,"Allele Count African":0,"Allele Number African":1632,"Homozygote Count African":0,"Allele Count East Asian":1,"Allele Number East Asian":2018,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":14696,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":1156,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":1758,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":268,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":9442,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738911,"RSID":".","Reference":"G","Alternate":"T","Consequence":"p.Glu156Asp","Protein Consequence":"p.Glu156Asp","Transcript Consequence":"c.468G>T","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":36846,"Number of Homozygotes":0,"Allele Frequency":0.00002714,"Allele Count African":0,"Allele Number African":1964,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":2516,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":18106,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":1420,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":2392,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":304,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":10144,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738912,"RSID":".","Reference":"A","Alternate":"G","Consequence":"p.Ser157Gly","Protein Consequence":"p.Ser157Gly","Transcript Consequence":"c.469A>G","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":4,"Allele Number":37870,"Number of Homozygotes":0,"Allele Frequency":0.0001056,"Allele Count African":0,"Allele Number African":2034,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":2596,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":4,"Allele Number European (Non-Finnish)":18736,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":1438,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":2504,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":310,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":10252,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738920,"RSID":".","Reference":"G","Alternate":"C","Consequence":"p.Pro159Pro","Protein Consequence":"p.Pro159Pro","Transcript Consequence":"c.477G>C","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":1,"Allele Number":50300,"Number of Homozygotes":0,"Allele Frequency":0.00001988,"Allele Count African":1,"Allele Number African":2776,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":3642,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":26156,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":2068,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":3934,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":370,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":11354,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738922,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.Pro160Leu","Protein Consequence":"p.Pro160Leu","Transcript Consequence":"c.479C>T","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":54212,"Number of Homozygotes":0,"Allele Frequency":0.00001845,"Allele Count African":0,"Allele Number African":3016,"Homozygote Count African":0,"Allele Count East Asian":1,"Allele Number East Asian":3972,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":28480,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":2270,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":4394,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":400,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":11680,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738922,"RSID":".","Reference":"C","Alternate":"G","Consequence":"p.Pro160Arg","Protein Consequence":"p.Pro160Arg","Transcript Consequence":"c.479C>G","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":54212,"Number of Homozygotes":0,"Allele Frequency":0.00001845,"Allele Count African":1,"Allele Number African":3016,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":3972,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":28480,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":2270,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":4394,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":400,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":11680,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738923,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.Pro160Pro","Protein Consequence":"p.Pro160Pro","Transcript Consequence":"c.480C>T","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":1,"Allele Number":55552,"Number of Homozygotes":0,"Allele Frequency":0.000018,"Allele Count African":1,"Allele Number African":3092,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":4120,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":29266,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":2350,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":4522,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":406,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":11796,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738931,"RSID":".","Reference":"C","Alternate":"G","Consequence":"p.Pro163Arg","Protein Consequence":"p.Pro163Arg","Transcript Consequence":"c.488C>G","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":65992,"Number of Homozygotes":0,"Allele Frequency":0.00001515,"Allele Count African":0,"Allele Number African":3784,"Homozygote Count African":0,"Allele Count East Asian":1,"Allele Number East Asian":4978,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":35308,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":2970,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":5892,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":482,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":12578,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738937,"RSID":".","Reference":"G","Alternate":"A","Consequence":"p.Arg165Gln","Protein Consequence":"p.Arg165Gln","Transcript Consequence":"c.494G>A","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":2,"Allele Number":76012,"Number of Homozygotes":0,"Allele Frequency":0.00002631,"Allele Count African":0,"Allele Number African":4438,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":5766,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":41020,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":3570,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":7288,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":562,"Homozygote Count Other":0,"Allele Count South Asian":2,"Allele Number South Asian":13368,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738944,"RSID":".","Reference":"G","Alternate":"A","Consequence":"p.Gly167Gly","Protein Consequence":"p.Gly167Gly","Transcript Consequence":"c.501G>A","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":1,"Allele Number":83336,"Number of Homozygotes":0,"Allele Frequency":0.000012,"Allele Count African":0,"Allele Number African":4972,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":6366,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":45230,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":3946,"Homozygote Count Finnish":0,"Allele Count Latino":1,"Allele Number Latino":8376,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":608,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":13838,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738946,"RSID":".","Reference":"G","Alternate":"A","Consequence":"p.Ser168Asn","Protein Consequence":"p.Ser168Asn","Transcript Consequence":"c.503G>A","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":84678,"Number of Homozygotes":0,"Allele Frequency":0.00001181,"Allele Count African":0,"Allele Number African":5094,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":6462,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":46004,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":4020,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":8554,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":616,"Homozygote Count Other":0,"Allele Count South Asian":1,"Allele Number South Asian":13928,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738953,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.Ser170Ser","Protein Consequence":"p.Ser170Ser","Transcript Consequence":"c.510C>T","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":2,"Allele Number":94508,"Number of Homozygotes":0,"Allele Frequency":0.00002116,"Allele Count African":0,"Allele Number African":5966,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":7270,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":51458,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":2,"Allele Number Finnish":4768,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":9786,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":680,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":14580,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738956,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.Arg171Arg","Protein Consequence":"p.Arg171Arg","Transcript Consequence":"c.513C>T","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":3,"Allele Number":97772,"Number of Homozygotes":0,"Allele Frequency":0.00003068,"Allele Count African":0,"Allele Number African":6270,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":7482,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":53276,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":5068,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":10120,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":702,"Homozygote Count Other":0,"Allele Count South Asian":2,"Allele Number South Asian":14854,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738959,"RSID":".","Reference":"C","Alternate":"G","Consequence":"p.Ala172Ala","Protein Consequence":"p.Ala172Ala","Transcript Consequence":"c.516C>G","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":2,"Allele Number":100534,"Number of Homozygotes":0,"Allele Frequency":0.00001989,"Allele Count African":0,"Allele Number African":6546,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":7678,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":54824,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":5330,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":10388,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":714,"Homozygote Count Other":0,"Allele Count South Asian":2,"Allele Number South Asian":15054,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738962,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.Gly173Gly","Protein Consequence":"p.Gly173Gly","Transcript Consequence":"c.519C>T","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":1,"Allele Number":103172,"Number of Homozygotes":0,"Allele Frequency":0.000009693,"Allele Count African":0,"Allele Number African":6852,"Homozygote Count African":0,"Allele Count East Asian":1,"Allele Number East Asian":7876,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":56266,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":5574,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":10602,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":736,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":15266,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738964,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.Pro174Leu","Protein Consequence":"p.Pro174Leu","Transcript Consequence":"c.521C>T","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":2,"Allele Number":104430,"Number of Homozygotes":0,"Allele Frequency":0.00001915,"Allele Count African":0,"Allele Number African":6976,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":7972,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":2,"Allele Number European (Non-Finnish)":56992,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":5688,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":10688,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":742,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":15372,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738965,"RSID":".","Reference":"C","Alternate":"T","Consequence":"p.Pro174Pro","Protein Consequence":"p.Pro174Pro","Transcript Consequence":"c.522C>T","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":6,"Allele Number":104952,"Number of Homozygotes":0,"Allele Frequency":0.00005717,"Allele Count African":5,"Allele Number African":7026,"Homozygote Count African":0,"Allele Count East Asian":1,"Allele Number East Asian":8004,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":57300,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":5732,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":10728,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":748,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":15414,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738965,"RSID":".","Reference":"C","Alternate":"G","Consequence":"p.Pro174Pro","Protein Consequence":"p.Pro174Pro","Transcript Consequence":"c.522C>G","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":3,"Allele Number":104952,"Number of Homozygotes":0,"Allele Frequency":0.00002858,"Allele Count African":2,"Allele Number African":7026,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":8004,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":57300,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":5732,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":10728,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":748,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":15414,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738966,"RSID":".","Reference":"G","Alternate":"A","Consequence":"p.Gly175Ser","Protein Consequence":"p.Gly175Ser","Transcript Consequence":"c.523G>A","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":3,"Allele Number":105824,"Number of Homozygotes":0,"Allele Frequency":0.00002835,"Allele Count African":0,"Allele Number African":7130,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":8068,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":0,"Allele Number European (Non-Finnish)":57788,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":5824,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":10788,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":754,"Homozygote Count Other":0,"Allele Count South Asian":3,"Allele Number South Asian":15472,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738966,"RSID":".","Reference":"G","Alternate":"T","Consequence":"p.Gly175Cys","Protein Consequence":"p.Gly175Cys","Transcript Consequence":"c.523G>T","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":6,"Allele Number":105824,"Number of Homozygotes":0,"Allele Frequency":0.0000567,"Allele Count African":1,"Allele Number African":7130,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":8068,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":5,"Allele Number European (Non-Finnish)":57788,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":5824,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":10788,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":754,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":15472,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738970,"RSID":".","Reference":"G","Alternate":"C","Consequence":"p.Arg176Pro","Protein Consequence":"p.Arg176Pro","Transcript Consequence":"c.527G>C","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":107808,"Number of Homozygotes":0,"Allele Frequency":0.000009276,"Allele Count African":0,"Allele Number African":7384,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":8174,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":58936,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":6016,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":10902,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":770,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":15626,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738975,"RSID":".","Reference":"T","Alternate":"G","Consequence":"p.Ser178Ala","Protein Consequence":"p.Ser178Ala","Transcript Consequence":"c.532T>G","Filter":"PASS","Annotation":"missense","Flags":"","Allele Count":1,"Allele Number":109692,"Number of Homozygotes":0,"Allele Frequency":0.000009116,"Allele Count African":0,"Allele Number African":7644,"Homozygote Count African":0,"Allele Count East Asian":0,"Allele Number East Asian":8246,"Homozygote Count East Asian":0,"Allele Count European (Non-Finnish)":1,"Allele Number European (Non-Finnish)":60002,"Homozygote Count European (Non-Finnish)":0,"Allele Count Finnish":0,"Allele Number Finnish":6208,"Homozygote Count Finnish":0,"Allele Count Latino":0,"Allele Number Latino":11008,"Homozygote Count Latino":0,"Allele Count Other":0,"Allele Number Other":792,"Homozygote Count Other":0,"Allele Count South Asian":0,"Allele Number South Asian":15792,"Homozygote Count South Asian":0},
{"Chrom":6,"Position":43738977,"RSID":"rs25648","Reference":"C","Alternate":"T","Consequence":"p.Ser178Ser","Protein Consequence":"p.Ser178Ser","Transcript Consequence":"c.534C>T","Filter":"PASS","Annotation":"synonymous","Flags":"","Allele Count":17511,"Allele Number":111092,"Number of Homozygotes":1402,"Allele Frequency":0.1576,"Allele Count African":708,"Allele Number African":7786,"Homozygote Count African":19,"Allele Count East Asian":691,"Allele Number East Asian":8280,"Homozygote Count East Asian":34,"Allele Count European (Non-Finnish)":10443,"Allele Number European (Non-Finnish)":60798,"Homozygote Count European (Non-Finnish)":869,"Allele Count Finnish":1221,"Allele Number Finnish":6358,"Homozygote Count Finnish":112,"Allele Count Latino":1834,"Allele Number Latino":11094,"Homozygote Count Latino":141,"Allele Count Other":129,"Allele Number Other":812,"Homozygote Count Other":10,"Allele Count South Asian":2485,"Allele Number South Asian":15964,"Homozygote Count South Asian":217}];

var circ = new VisCircularBarChart({
  el: rootDiv,
  data: alleleFreq,
  dataTitle: "Position",
  displayedVal: "Allele Frequency",
  color: "darkred"
});

console.log("circ instance: " + circ.hello);

// app.getData(rootDiv, url, redditPath, app.render, app); // works with the pokeapi
// app.render(rootDiv, myData, "purple"); // works with mock data myData
circ.hello("JJ");
circ.render();
// app.getJSON('vegfa-exac.json');


